{
  "comments": [
    {
      "key": {
        "uuid": "5a682502_e8e6ce15",
        "filename": "sdnvpn/lib/utils.py",
        "patchSetId": 6
      },
      "lineNbr": 1008,
      "author": {
        "id": 7381
      },
      "writtenOn": "2018-09-14T18:13:50Z",
      "side": 1,
      "message": "next() here can produce StopIteration error. You should try to catch that and return False if it occurs.",
      "range": {
        "startLine": 1008,
        "startChar": 51,
        "endLine": 1008,
        "endChar": 57
      },
      "revId": "8726211106f489cd51ff65547cc684541a59d100",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a682502_22d1f9fb",
        "filename": "sdnvpn/lib/utils.py",
        "patchSetId": 6
      },
      "lineNbr": 1102,
      "author": {
        "id": 7381
      },
      "writtenOn": "2018-09-21T13:06:13Z",
      "side": 1,
      "message": "vm_output may be None. you should check it first",
      "range": {
        "startLine": 1102,
        "startChar": 18,
        "endLine": 1102,
        "endChar": 53
      },
      "revId": "8726211106f489cd51ff65547cc684541a59d100",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a682502_c273e5af",
        "filename": "sdnvpn/test/functest/config.yaml",
        "patchSetId": 6
      },
      "lineNbr": 41,
      "author": {
        "id": 7381
      },
      "writtenOn": "2018-09-21T09:11:40Z",
      "side": 1,
      "message": "change to artifacts/testcase_1bis.yaml",
      "range": {
        "startLine": 41,
        "startChar": 19,
        "endLine": 41,
        "endChar": 53
      },
      "revId": "8726211106f489cd51ff65547cc684541a59d100",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a682502_0265dde0",
        "filename": "sdnvpn/test/functest/testcase_1bis.py",
        "patchSetId": 6
      },
      "lineNbr": 13,
      "author": {
        "id": 7381
      },
      "writtenOn": "2018-09-21T09:11:40Z",
      "side": 1,
      "message": "import pkg_resources",
      "range": {
        "startLine": 13,
        "startChar": 0,
        "endLine": 13,
        "endChar": 0
      },
      "revId": "8726211106f489cd51ff65547cc684541a59d100",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a682502_82a0cdf5",
        "filename": "sdnvpn/test/functest/testcase_1bis.py",
        "patchSetId": 6
      },
      "lineNbr": 58,
      "author": {
        "id": 7381
      },
      "writtenOn": "2018-09-21T09:11:40Z",
      "side": 1,
      "message": "file_path \u003d pkg_resources.resource_filename(\u0027sdnvpn\u0027, TESTCASE_CONFIG.hot_file_name)\ntempl \u003d open(file_path, \u0027r\u0027).read()",
      "range": {
        "startLine": 58,
        "startChar": 8,
        "endLine": 58,
        "endChar": 63
      },
      "revId": "8726211106f489cd51ff65547cc684541a59d100",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a682502_68a11ea9",
        "filename": "sdnvpn/test/functest/testcase_1bis.py",
        "patchSetId": 6
      },
      "lineNbr": 201,
      "author": {
        "id": 7381
      },
      "writtenOn": "2018-09-14T18:13:50Z",
      "side": 1,
      "message": "This method can raise SystemError. You do not catch it on purpose to elevate it further? If not then you should handle it here",
      "range": {
        "startLine": 201,
        "startChar": 19,
        "endLine": 201,
        "endChar": 40
      },
      "revId": "8726211106f489cd51ff65547cc684541a59d100",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}